---
# tasks file for adrianovieira.opensuse.osem
- import_tasks: tasks/CentOS-repos.yml
  when:
    - ansible_distribution|lower == "centos"
    - ansible_distribution_major_version == "7"
  tags:
    - webserver
    - setup
    - repos

- name: Install packages on CentOS-7
  when:
    - ansible_distribution|lower == "centos"
    - ansible_distribution_major_version == "7"
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - git
    - make
    - gcc
    - gcc-c++
    - libxml2-devel
    - libxslt-devel
    - nodejs
    - screen
    - mariadb-devel
    - sqlite-devel
    - ImageMagick
    - bzip2
    - libcurl-devel
    - httpd
    - httpd-devel
    - apr-devel
    - apr-util-devel
    - passenger
    - mod_passenger
  tags:
    - webserver
    - setup
    - packages

- name: install gem bundler on CentOS-7
  when:
    - ansible_distribution|lower == "centos"
    - ansible_distribution_major_version == "7"
  # ! $(gem list -i bundler)
  # gem_module didn't work for me so far
  shell: 'gem install --no-document bundler'
  tags:
    - webserver
    - setup
    - bundler

- name: install phantomjs
  when:
    - ansible_distribution|lower == "centos"
    - ansible_distribution_major_version == "7"
  unarchive:
    src: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    dest: /usr/local/bin
    remote_src: yes
    extra_opts:
      - --strip-components=2
      - phantomjs-2.1.1-linux-x86_64/bin/phantomjs
  tags:
    - webserver
    - setup
    - phantomjs
