---
# tasks file for adrianovieira.opensuse.osem
- import_tasks: tasks/CentOS.yml
  when:
    - ansible_distribution|lower == "centos"
    - ansible_distribution_major_version == "7"

- import_tasks: tasks/osem.yml
  tags:
    - webserver
    - osem
