---
# tasks file for adrianovieira.opensuse.osem
- import_role:
    name: geerlingguy.apache
  tags:
    - webserver
    - setup
    - osem
    - apache

- git:
    repo: 'https://github.com/openSUSE/osem.git'
    dest: '{{ osem_rootdir | mandatory }}'
    version: '{{ osem_release }}'
  tags:
    - webserver
    - deploy
    - osem
    - environment
