---
# tasks file for adrianovieira.opensuse.osem
- template:
    src: templates/osem-apache-vhost.conf.j2
    dest: /etc/httpd/conf.d/00-osem.conf
  when:
    - ansible_distribution|lower == "centos"
    - ansible_distribution_major_version == "7"
  tags:
    - webserver
    - setup
    - osem
    - vhost
