---
# tasks file for adrianovieira.opensuse.osem
- import_role:
    name: geerlingguy.apache
  tags:
    - webserver
    - setup
    - osem
    - apache

- git:
    repo: 'https://github.com/openSUSE/osem.git'
    dest: '{{ osem_rootdir | mandatory }}'
    version: '{{ osem_release }}'
  tags:
    - webserver
    - deploy
    - osem

- import_tasks: tasks/osem-setup.yml

- bundler:
    executable: /usr/local/bin/bundler
    chdir: '{{ osem_rootdir | mandatory }}'
    extra_args: '--deployment --without test development'
  tags:
    - webserver
    - deploy
    - osem
    - bundler

- name: run rake to generate assets
  shell:
    chdir: '{{ osem_rootdir }}'
    cmd:  "RAILS_ENV={{ osem_rails_env }} /usr/local/bin/bundle exec rake assets:precompile"
  register: result
  tags:
    - webserver
    - deploy
    - osem
    - assets
