---
# tasks file for adrianovieira.opensuse.osem
- template:
    src: dotenv-dist.j2
    dest: "{{osem_rootdir}}/.env.production"
    owner: apache
    group: apache
  when:
    - ansible_distribution|lower == "centos"
    - ansible_distribution_major_version == "7"
  tags:
    - webserver
    - setup
    - osem
    - environment

- file:
    path: "{{osem_rootdir}}"
    owner: apache
    group: apache
    recurse: yes
  when:
    - ansible_distribution|lower == "centos"
    - ansible_distribution_major_version == "7"
  tags:
    - webserver
    - setup
    - osem
    - environment

- template:
    src: database-dist.yml.j2
    dest: "{{osem_rootdir}}/config/database.yml"
    owner: apache
    group: apache
  when:
    - ansible_distribution|lower == "centos"
    - ansible_distribution_major_version == "7"
  tags:
    - webserver
    - setup
    - osem
    - environment
