---
# handlers file for adrianovieira.opensuse.osem
- name: yum-clean-metadata
  command: yum clean metadata
  args:
    warn: no

- name: restart apache
  service:
    name: httpd
    state: restarted
  listen: "restart web services"
  when:
    - ansible_distribution|lower == "centos"
    - ansible_distribution_major_version == "7"
